global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:4000']

  - job_name: 'ai-engine'
    static_configs:
      - targets: ['ai-engine:8000']
